// Generated by https://quicktype.io

export interface MovieResponse {
  imdbID: string;
  title: string;
  year: string;
  poster: string;
  actors: string;
  director: string;
  createdAt: string;
  updatedAt: string;
  id: string;
  estado: boolean;
  usuario: Usuario;
}

export interface Usuario {
  usuario_id: string;
  estado: boolean;
  usuario: string;
}
