// Generated by https://quicktype.io

export interface Movies {
  Search: Search[];
  totalResults: string;
  Response: string;
}

export interface Search {
  Title: string;
  Year: string;
  imdbID: string;
  Type: Type;
  Poster: string;
}

export enum Type {
  Game = 'game',
  Movie = 'movie',
  Series = 'series',
}
