// Generated by https://quicktype.io

export interface MovieFavoriteResponse {
  createdAt: string;
  updatedAt: string;
  id: string;
  imdbID: string;
  title: string;
  year: string;
  poster: string;
  actors: string;
  director: string;
  estado: boolean;
}
